### ISSUE TITLE
how to use this library 

### ISSUE THREAD

**Issue by dihiaselma** [imvab/news-yolo#1]

**Comment by imvab** [comment]
You can refer to my [article](https://towardsdatascience.com/object-detection-on-newspaper-images-using-yolov3-85acfa563080) on Medium.
Do star this if you liked it.

**Comment by dihiaselma** [comment]
thank you for your reply.
I want to expose you my problem.
I have an image of a newspaper. I want to extract its article one by one. I mean I don't want to get a raw text from the whole image. but part by part. 
how to do this?, Tesseract return me all the text in desorder.
